'use client'
import { useEffect, useMemo, useState } from 'react'
import { authFetch, errorText, newRequestKey, readJson } from '@/lib/authFetch'
import { networkOf, type Eip1193 } from '@/lib/wallet/eip1193'

type Config={id:string;chain_id:number;network:string;asset:string;symbol:string;receiving_address:string;fee_bps:number;fixed_fee:number;min_amount:number;max_amount:number|null;confirmations:number}
type Intent={intent_id:string;status:string;requested_amount:number;fee_amount:number;net_amount:number;receiving_address:string;network:string;symbol:string;expires_at:string}
const decimalToHex=(value:string)=>{const clean=value.trim();if(!/^\d+(?:\.\d{1,18})?$/.test(clean))throw new Error('Enter a valid amount.');const [whole,frac='']=clean.split('.');return '0x'+(BigInt(whole)*10n**18n+BigInt((frac+'0'.repeat(18)).slice(0,18))).toString(16)}
const fmtAmount=(n:number)=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:8}):'—'

export function WalletDepositPanel({provider,address,chainId,walletId}:{provider:Eip1193;address:string;chainId:number;walletId:string}){
  const [configs,setConfigs]=useState<Config[]>([]),[amount,setAmount]=useState(''),[config,setConfig]=useState<Config|null>(null),[intent,setIntent]=useState<Intent|null>(null)
  const [busy,setBusy]=useState<'load'|'prepare'|'send'|'verify'|''>(''),[error,setError]=useState(''),[message,setMessage]=useState('')
  useEffect(()=>{let alive=true;authFetch('/api/client/wallet-deposits').then(r=>readJson<{configs:Config[]}>(r)).then(v=>{if(alive)setConfigs(v.configs||[])}).catch(e=>{if(alive)setError(errorText(e))});return()=>{alive=false}},[])
  const current=useMemo(()=>configs.find(c=>c.chain_id===chainId)||null,[configs,chainId]);useEffect(()=>setConfig(current),[current])
  const createIntent=async()=>{setError('');setMessage('');if(!config){setError('Deposits are not enabled for this network yet.');return}if(!/^\d+(?:\.\d{1,18})?$/.test(amount.trim())){setError('Enter a valid amount.');return}const n=Number(amount);if(!Number.isFinite(n)||n<=0){setError('Enter a valid amount.');return}setBusy('prepare');try{const r=await readJson<{intent:Intent}>(await authFetch('/api/client/wallet-deposits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wallet_id:walletId,amount:n,idempotency_key:newRequestKey()})}));setIntent(r.intent)}catch(e){setError(errorText(e))}finally{setBusy('')}}
  const verifyTx=async(txHash:string)=>{setBusy('verify');try{const v=await readJson<{status:string;confirmations?:number;required_confirmations?:number}>(await authFetch('/api/client/wallet-deposits/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intent_id:intent?.intent_id,tx_hash:txHash})}));if(v.status==='pending_verification')setMessage('Transaction submitted. Waiting for blockchain confirmation ('+(v.confirmations||0)+'/'+(v.required_confirmations||1)+').');else{setMessage('Transfer received and credited to your Tarafab Account Balance after blockchain verification.');setIntent(null);setAmount('')}}catch(e){setError(errorText(e))}finally{setBusy('')}}
  const send=async()=>{if(!intent)return;setError('');setMessage('');setBusy('send');try{const txHash=await provider.request({method:'eth_sendTransaction',params:[{from:address,to:intent.receiving_address,value:decimalToHex(String(intent.requested_amount))}]}) as string;if(!/^0x[0-9a-fA-F]{64}$/.test(txHash))throw new Error('The wallet did not return a valid transaction hash.');await verifyTx(txHash)}catch(e){setError(errorText(e));setBusy('')}}
  const net=networkOf(chainId)
  return <div className="panel p-4 sm:p-5"><div><h3 className="text-[15px] font-semibold text-fg">Transfer to Tarafab</h3><p className="mt-1 text-sm text-fg-muted">Send native {net?.symbol||'asset'} from this connected wallet into your Tarafab Account Balance. Your wallet signs the transaction; Tarafab never receives your private key.</p></div>
    {!config?<div className="mt-4 alert alert-info text-sm">Deposits are not enabled for {net?.name||'this network'} yet. An admin must configure a Tarafab receiving address first.</div>:!intent?<div className="mt-4 space-y-3"><label className="block"><span className="block text-[13px] text-fg-muted mb-1.5">Amount ({config.symbol})</span><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} className="field" placeholder={config.min_amount?'Min '+config.min_amount:'0.00'}/></label><div className="rounded-lg border border-ink-700 bg-ink-900/40 p-3 text-[12px] text-fg-muted"><div className="flex justify-between gap-3"><span>Tarafab service fee</span><span>{amount?'Calculated when you review':'—'}</span></div><p className="mt-1 text-fg-faint">The exact fee and amount credited are shown before the wallet transaction is requested.</p></div><button onClick={createIntent} disabled={!!busy} className="btn btn-solid w-full sm:w-auto">{busy==='prepare'?'Preparing…':'Review transfer'}</button></div>
    :<div className="mt-4 space-y-3"><div className="rounded-lg border border-ink-700 bg-ink-900/40 p-3 text-sm"><div className="flex justify-between gap-3"><span className="text-fg-muted">You send</span><strong>{fmtAmount(Number(intent.requested_amount))} {intent.symbol}</strong></div><div className="flex justify-between gap-3 mt-1"><span className="text-fg-muted">Tarafab service fee</span><strong>{fmtAmount(Number(intent.fee_amount))} {intent.symbol}</strong></div><div className="flex justify-between gap-3 mt-1 border-t border-ink-700 pt-2"><span>Credited to Account Balance</span><strong>{fmtAmount(Number(intent.net_amount))} {intent.symbol}</strong></div><p className="mt-2 text-[11px] text-fg-faint break-all">Receiving address: {intent.receiving_address}</p></div><div className="flex flex-col sm:flex-row gap-2"><button onClick={()=>setIntent(null)} disabled={!!busy} className="btn btn-ghost">Back</button><button onClick={send} disabled={!!busy} className="btn btn-solid sm:ml-auto">{busy==='send'?'Open wallet…':busy==='verify'?'Verifying…':'Send '+intent.requested_amount+' '+intent.symbol}</button></div><p className="text-[11px] text-fg-faint">Network fees are charged by the blockchain/wallet separately. The Tarafab service fee above is not a network fee.</p></div>}
    {error&&<div className="alert alert-danger mt-4 text-sm">{error}</div>}{message&&<div className="alert alert-success mt-4 text-sm">{message}</div>}
  </div>
}
