'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
type Row={chain_id:number;network:string;symbol:string;receiving_address:string;enabled:boolean;fee_bps:number;fixed_fee:number;min_amount:number;max_amount:number|null;confirmations:number}
const NETWORKS:[number,string][]=[[1,'Ethereum'],[8453,'Base'],[42161,'Arbitrum One'],[10,'OP Mainnet'],[137,'Polygon'],[56,'BNB Smart Chain']]
export function WalletDepositConfig(){
 const supabase=createClient(),[rows,setRows]=useState<Row[]>([]),[form,setForm]=useState<Row>({chain_id:56,network:'BNB Smart Chain',symbol:'BNB',receiving_address:'',enabled:false,fee_bps:100,fixed_fee:0,min_amount:0,max_amount:null,confirmations:1}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState('')
 const load=async()=>{const {data,error}=await (supabase.rpc as any)('admin_list_wallet_deposit_configs');if(error){setError(error.message);return}setRows(data||[])}
 useEffect(()=>{void load()},[])
 const save=async()=>{setBusy(true);setError('');setDone('');try{const {error}=await (supabase.rpc as any)('admin_upsert_wallet_deposit_config',{p_chain_id:form.chain_id,p_receiving_address:form.receiving_address.trim(),p_enabled:form.enabled,p_fee_bps:form.fee_bps,p_fixed_fee:form.fixed_fee,p_min_amount:form.min_amount,p_max_amount:form.max_amount,p_confirmations:form.confirmations});if(error)throw error;setDone('Deposit configuration saved.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <div className="glass rounded-2xl border border-white/[0.08] p-4 sm:p-5 mt-5"><h3 className="text-sm font-semibold text-white">External wallet deposits</h3><p className="text-xs text-slate-400 mt-1">Configure the public Tarafab receiving address, service fee and confirmation requirement. Never enter a private key or recovery phrase.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">
 <label className="text-xs text-slate-400">Network<select value={form.chain_id} onChange={e=>{const n=NETWORKS.find(x=>x[0]===Number(e.target.value))!;setForm(f=>({...f,chain_id:n[0],network:n[1],symbol:n[1]==='BNB Smart Chain'?'BNB':n[1]==='Polygon'?'POL':'ETH'}))}} className="input-field w-full mt-1">{NETWORKS.map(n=><option key={n[0]} value={n[0]}>{n[1]}</option>)}</select></label>
 <label className="text-xs text-slate-400">Tarafab receiving address<input value={form.receiving_address} onChange={e=>setForm(f=>({...f,receiving_address:e.target.value}))} className="input-field w-full mt-1" placeholder="0x…" /></label>
 <label className="text-xs text-slate-400">Percentage fee (basis points)<input type="number" min="0" max="10000" value={form.fee_bps} onChange={e=>setForm(f=>({...f,fee_bps:Number(e.target.value)}))} className="input-field w-full mt-1"/><span className="block text-[11px] text-slate-500 mt-1">100 bps = 1%</span></label>
 <label className="text-xs text-slate-400">Fixed fee<input type="number" min="0" step="0.00000001" value={form.fixed_fee} onChange={e=>setForm(f=>({...f,fixed_fee:Number(e.target.value)}))} className="input-field w-full mt-1"/></label>
 <label className="text-xs text-slate-400">Minimum deposit<input type="number" min="0" step="0.00000001" value={form.min_amount} onChange={e=>setForm(f=>({...f,min_amount:Number(e.target.value)}))} className="input-field w-full mt-1"/></label>
 <label className="text-xs text-slate-400">Maximum deposit<input type="number" min="0" step="0.00000001" value={form.max_amount??''} onChange={e=>setForm(f=>({...f,max_amount:e.target.value===''?null:Number(e.target.value)}))} className="input-field w-full mt-1" placeholder="No limit"/></label>
 <label className="text-xs text-slate-400">Required confirmations<input type="number" min="1" max="100" value={form.confirmations} onChange={e=>setForm(f=>({...f,confirmations:Number(e.target.value)}))} className="input-field w-full mt-1"/></label>
 <label className="flex items-center gap-2 text-xs text-slate-300 mt-5"><input type="checkbox" checked={form.enabled} onChange={e=>setForm(f=>({...f,enabled:e.target.checked}))}/> Enable deposits on this network</label>
 </div><div className="mt-4 flex gap-2"><button onClick={save} disabled={busy} className="text-sm font-semibold text-white bg-violet-600 hover:bg-violet-500 rounded-xl px-4 py-2.5 disabled:opacity-60">{busy?'Saving…':'Save configuration'}</button>{done&&<span className="text-xs text-emerald-400 self-center">{done}</span>}</div>{error&&<p className="text-xs text-red-400 mt-3">{error}</p>}
 {rows.length>0&&<div className="mt-5 border-t border-white/[0.08] pt-4"><p className="text-xs text-slate-500 mb-2">Configured networks</p>{rows.map(r=><div key={r.chain_id} className="flex flex-wrap justify-between gap-2 text-xs py-2 border-b border-white/[0.05]"><span className="text-slate-200">{r.network} · {r.symbol}</span><span className={r.enabled?'text-emerald-400':'text-slate-500'}>{r.enabled?'Enabled':'Disabled'} · {(r.fee_bps/100).toFixed(2)}%</span></div>)}</div>}
 </div>
}
